from langchain_ollama import OllamaLLM
from langchain.chains import RetrievalQA
from vector_store import get_vector_store
from dotenv import load_dotenv


# Load environment variables

llm = OllamaLLM(model="mistral",base_url="http://localhost:11434", temperature=0.7)


vector_store = get_vector_store()
retriever = vector_store.as_retriever()

# Setup RAG chain
qa_chain = RetrievalQA.from_chain_type(llm=llm, chain_type="stuff", retriever=retriever)
print(qa_chain)



def chatbot_agent(query: str) -> str:
    """
    Processes a user query using a Retrieval-Augmented Generation (RAG) approach,
    combining the strengths of vector-based document retrieval and a large language model (LLM)
    for accurate and context-aware responses.

    Workflow:
    1. The function first attempts to answer the query by using a RAG pipeline:
       - It retrieves relevant documents from a vector store (e.g., FAISS, Chroma) based on the query.
       - These documents are then passed to a language model (e.g., Gemini-Pro via LangChain) 
         to generate an informed and grounded answer.

    2. If the RAG response is unsatisfactory — for example, if the answer is empty,
       unclear, or includes fallback phrases like "I don't know" — the function automatically
       switches to a fallback mechanism.

    3. In fallback mode, the function directly invokes the language model (LLM) to answer the query
       using its general knowledge, without relying on external documents.

    This hybrid approach ensures:
    - High accuracy when relevant documents are available.
    - Broader general-purpose answers when the document store lacks sufficient context.

    Parameters:
    ----------
    query : str
        The user input or question to be processed.

    Returns:
    -------
    str
        A human-readable answer generated by the RAG system or directly from the LLM as a fallback.
    """
    try:
        result = qa_chain.invoke(query)
        response_text = result["result"] if isinstance(result, dict) and "result" in result else str(result)
    except Exception as e:
        return f"Error during processing: {str(e)}"
    
    fallback_phrases = ["I don't know", "I'm not sure", "can't find"]
    if not response_text or any(phrase.lower() in response_text.lower() for phrase in fallback_phrases):
        try:
            response_text = llm.invoke(
                f"Provide a helpful and accurate answer to the following user query, even without specific documents: {query}"
            )
        except Exception as e:
            return f"LLM fallback error: {str(e)}"
    
    return response_text
