from langchain.llms import HuggingFaceHub
from langchain.chains import RetrievalQA
from vector_store import get_vector_store
from dotenv import load_dotenv


# Load environment variables
load_dotenv()
llm = HuggingFaceHub(
    repo_id="google/flan-t5-small",
    model_kwargs={"temperature": 0.5, "max_new_tokens": 200}
)


vector_store = get_vector_store()
retriever = vector_store.as_retriever()

# Setup RAG chain
qa_chain = RetrievalQA.from_chain_type(llm=llm, retriever=retriever)
print(qa_chain)



def chatbot_agent(query: str) -> str:
    """
    Processes a user query using a Retrieval-Augmented Generation (RAG) approach,
    combining the strengths of vector-based document retrieval and a large language model (LLM)
    for accurate and context-aware responses.

    Workflow:
    1. The function first attempts to answer the query by using a RAG pipeline:
       - It retrieves relevant documents from a vector store (e.g., FAISS, Chroma) based on the query.
       - These documents are then passed to a language model (e.g., Gemini-Pro via LangChain) 
         to generate an informed and grounded answer.

    2. If the RAG response is unsatisfactory — for example, if the answer is empty,
       unclear, or includes fallback phrases like "I don't know" — the function automatically
       switches to a fallback mechanism.

    3. In fallback mode, the function directly invokes the language model (LLM) to answer the query
       using its general knowledge, without relying on external documents.

    This hybrid approach ensures:
    - High accuracy when relevant documents are available.
    - Broader general-purpose answers when the document store lacks sufficient context.

    Parameters:
    ----------
    query : str
        The user input or question to be processed.

    Returns:
    -------
    str
        A human-readable answer generated by the RAG system or directly from the LLM as a fallback.
    """
    try:
        # Step 1: Try to get an answer using the Retrieval-Augmented Generation pipeline
        # This uses the vector store to fetch relevant documents and then passes them to the LLM
        response = qa_chain.invoke(query)
    except Exception as e:
        # If any error occurs during RAG processing, return the error message
        return f"Error during processing: {str(e)}"
    
    # Step 2: Check if the response is weak or unsatisfactory
    # Common weak phrases that indicate the RAG system couldn't find a strong answer
    fallback_phrases = ["I don't know", "I'm not sure", "can't find"]
    if not response or any(phrase.lower() in response.lower() for phrase in fallback_phrases):
        try:
            # Step 3: Fall back to using the LLM directly, without documents
            # This leverages the model's own training and general knowledge
            response = llm.invoke(
                f"Provide a helpful and accurate answer to the following user query, even without specific documents: {query}"
            )
        except Exception as e:
            # If fallback also fails, return error message
            return f"LLM fallback error: {str(e)}"
    
    # Return the final response (either from RAG or fallback)
    return response
